### ISSUE TITLE
Vertical scrolling.

### ISSUE THREAD

**Issue by digital230** [masonwongcs/react-simple-marquee#8]
Hi, Thanks for this package. i have a question can we render vertical content.

**Comment by masonwongcs** [comment]
Hi @digital230 thanks for using my library, do you want to create a pull request for this? I will work on it.

**Comment by kevinkam** [comment]
@digital230 I will try to work on it on weekend.

**Comment by digital230** [comment]
@masonwongcs  sorry for late reply .. unfortunately not, i am busy with current project. @kevinkam  thanks you can work on it anytime i have legacy vertical Marquee right now which is working fine for now.

**Comment by masonwongcs** [comment]
Hi @digital230 we had deployed the latest version of 1.2.2 with direction feature.
